### ISSUE TITLE
Winget packages 

### ISSUE THREAD

**Issue by VSBernhard** [rink-turksma/IntunePrepTool#1]
WinGet search function not working

**Comment by rink-turksma** [comment]
Hi, 

Thanks for your feedback..
Can you test if winget is working for you in the Command line:
"Winget search VLC' for example"
If you need to accept any licenses. Do that.
If winget is not found:
Please install latest stable release from: https://github.com/microsoft/winget-cli
Also needed for the Winget package option on the target machine.

Let me know if this is working for you.

Greetings,
Rink
