### ISSUE TITLE
IntunePrep Tool Install location not found!

### ISSUE THREAD

**Issue by MahdiDK** [rink-turksma/IntunePrepTool#2]
i have set it up without any issue. however the download function is not working.
![error](https://github.com/rink-turksma/IntunePrepTool/assets/47952891/6642b302-7f92-458a-be32-d182ecdff178)
![image](https://github.com/rink-turksma/IntunePrepTool/assets/47952891/594fbe37-3042-47dc-811e-641a60cd1d30)

**Comment by rink-turksma** [comment]
Hi,

Thanks for your feedback!
Did you install the IntunePrepTool with Winget or an MSI installable?
The script checks this by checking if the install directory exists.
Please let me know.
![image](https://github.com/rink-turksma/IntunePrepTool/assets/127322820/75902211-0251-48cf-b208-c09756c7350d)

**Comment by MahdiDK** [comment]
i used winget. it is installed on C:\Program Files\IntunePrepTool as i have 64bit system. maybe you need to add a condition for both pathes

**Comment by rink-turksma** [comment]
Hi,

Yes! I was just typing. I found the mistake.
Thanks!!!
The fix will be available next Monday.

Greetings

**Comment by rink-turksma** [comment]
Fix is online.
Winget version will be updated monday i think.
MSI Version 1.2.6.0 should work.
https://github.com/rink-turksma/IntunePrepTool/releases
